# Labels: define labels for Issues and Pull Requests
labels:
  - name: âš ï¸ kritisk
    color: c01100
    description: StÃ¸rre feil som hindrer videre utvikling / bruk
  - name: ğŸŒŸ ny funksjonalitet
    color: 96bc42
    description: Endring som tilfÃ¸rer funksjonalitet vi ikke har
  - name: ğŸ duplikat
    oldname: duplicate
    color: feea6d
    description: Det finnes et lignende / likt issue
  - name: ğŸ” Stor
    color: ee9307
    description: StÃ¸rre endringer som vil ta vesentlig tid Ã¥ fikse
  - name: ğŸ› bug
    oldname: bug
    color: dd2e19
    description: Noe som ikke virker
  - name: ğŸ‘¨ğŸ¼â€ğŸ’» forbedring
    oldname: enhancement
    color: 65d5fd
    description: Forbedring av eksisterende funksjon
  - name: ğŸ’” skjerikke
    oldname: wontfix
    color: 000000
    description: Dette blir ikke fulgt opp
  - name: ğŸ“– Tekst
    color: 5794fe
    description: NÃ¥r det holder Ã¥ endre teksten
  - name: ğŸ¤“ Brukeropplevelse
    color: 3163d4
    description: Forbedringer i brukeropplevelsen
